import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LeftNavbar from "./components/LeftNavbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const types = await fetch(process.env.GITHUB_RAW_URL + "/resources.json", {
    method: "GET",
    headers: {
      contentType: "application/json",
    },
    next: {
      revalidate: 1,
    },
  })
    .then((res) => res.json())
    ?.then((data) => Object.keys(data))
    ?.then((types) =>
      types.map((type) => `${type.charAt(0).toUpperCase()}${type.slice(1)}`)
    );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col">
          <div className="h-28 bg-gray-700 text-white p-5 w-full">
            <h1 className="text-3xl font-bold">Free Learning Resources</h1>
          </div>
          <div className="grid grid-cols-12 h-full">
            <div className="relative left-0 col-span-1 bg-gray-800 text-white">
              <LeftNavbar types={types} />
            </div>
            <div className="p-5 h-full overflow-y-auto col-span-11 flex-1">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
