import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LeftNavbar from "./components/LeftNavbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col">
          <div className="h-28 bg-gray-700 text-white p-5 w-full">
            <h1 className="text-3xl font-bold">Free Learning Resources</h1>
          </div>
          <div className="grid grid-cols-12 h-full">
            <div className="relative left-0 col-span-1 bg-gray-800 text-white">
              <LeftNavbar />
            </div>
            <div className="p-5 h-full overflow-y-auto col-span-11 flex-1">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
